import { randomUUID } from 'node:crypto'

/**
 * In-memory confirmation-code store for dangerous operations (Principle 14).
 *
 * A dangerous mutation that arrives without a valid `x-anas-confirm` header is
 * answered with 409 + a freshly generated code (see {@link confirmGate}). The
 * client shows the server's warnings and resends with the code; we verify it,
 * consume it (single-use), and let the operation proceed.
 *
 * Codes are:
 *   - Generated by anasd (crypto-random, never Math.random)
 *   - Tied to a specific operation signature (operation + params)
 *   - Time-limited (default 2 min)
 *   - Single-use (consumed on a successful verify)
 *   - Verified server-side (the client can't fabricate one)
 *
 * The clock is injectable so expiry is deterministic in tests. Reading Date.now
 * at call time inside the daemon runtime is fine — the ban is on module-top
 * time/randomness in workflow scripts, not here.
 */

export interface ConfirmStoreOptions {
  /** Code lifetime in milliseconds. Default 120_000 (2 minutes). */
  ttlMs?: number
  /** Injectable clock for tests. Default () => Date.now(). */
  now?: () => number
}

interface ConfirmEntry {
  /** Operation signature this code authorizes (operation + params + bound id). */
  signature: string
  /** The signature WITHOUT the bound id — what a name-only match compares. */
  base: string
  /**
   * The stable id the code was minted under (story ident.1: a pool or dataset
   * guid, a snapshot's createtxg), when the gate bound one.
   */
  bound?: Record<string, string>
  /** Absolute expiry, epoch ms. */
  expiresAt: number
}

/** The stable id a confirm is bound to: a few named string facts (`{ guid }`). */
export type BoundId = Record<string, string>

/** A generated code plus its ISO-8601 expiry (for the X-Anas-Confirm-Expires header). */
export interface GeneratedConfirm {
  code: string
  expiresAt: string
}

const HYPHENS = /-/g

/** Stable JSON: object keys sorted so signatures are order-independent. */
function stableStringify(value: unknown): string {
  if (value === null || typeof value !== 'object')
    return JSON.stringify(value) ?? 'null'
  if (Array.isArray(value))
    return `[${value.map(stableStringify).join(',')}]`
  const obj = value as Record<string, unknown>
  const keys = Object.keys(obj).sort()
  return `{${keys.map(k => `${JSON.stringify(k)}:${stableStringify(obj[k])}`).join(',')}}`
}

export class ConfirmStore {
  private entries = new Map<string, ConfirmEntry>()
  private ttlMs: number
  private now: () => number

  constructor(opts?: ConfirmStoreOptions) {
    this.ttlMs = opts?.ttlMs ?? 120_000
    this.now = opts?.now ?? (() => Date.now())
  }

  /** Canonical signature for an operation + its resource params (+ the bound id). */
  private signature(operation: string, params: Record<string, unknown>, bound?: BoundId): string {
    const base = `${operation} ${stableStringify(params)}`
    return bound ? `${base} ${stableStringify(bound)}` : base
  }

  /** Drop expired entries so the map doesn't grow unbounded. */
  private prune(): void {
    const t = this.now()
    for (const [code, entry] of this.entries) {
      if (entry.expiresAt <= t)
        this.entries.delete(code)
    }
  }

  /**
   * Generate and store a code for an operation. Returns the code and its ISO
   * expiry. The code is crypto-random (hyphen-stripped UUID, first 12 chars).
   */
  generateCode(operation: string, params: Record<string, unknown>, bound?: BoundId): GeneratedConfirm {
    this.prune()
    const code = randomUUID().replace(HYPHENS, '').slice(0, 12)
    const expiresAt = this.now() + this.ttlMs
    this.entries.set(code, {
      signature: this.signature(operation, params, bound),
      base: this.signature(operation, params),
      ...(bound ? { bound: { ...bound } } : {}),
      expiresAt,
    })
    return { code, expiresAt: new Date(expiresAt).toISOString() }
  }

  /**
   * Verify a code against an operation signature. Consumes the code on success
   * (single-use). Returns false for unknown, expired, or mismatched codes; an
   * expired code is also evicted.
   */
  verifyCode(code: string, operation: string, params: Record<string, unknown>, bound?: BoundId): boolean {
    const entry = this.entries.get(code)
    if (!entry)
      return false
    if (entry.expiresAt <= this.now()) {
      this.entries.delete(code)
      return false
    }
    if (entry.signature !== this.signature(operation, params, bound))
      return false
    this.entries.delete(code)
    return true
  }

  /**
   * Story ident.1: was `code` minted for this exact operation and params but
   * under a DIFFERENT bound id? Returns the id it was minted under (and
   * consumes the code — it can never verify again), or null when the code is
   * unknown, expired, for another operation/params, or for the same id. This
   * is how a gate tells "the object under that name changed since you
   * confirmed" apart from a plain missing or stale code.
   */
  takeBoundMismatch(code: string, operation: string, params: Record<string, unknown>, bound: BoundId): BoundId | null {
    const entry = this.entries.get(code)
    if (!entry || entry.expiresAt <= this.now() || !entry.bound)
      return null
    if (entry.base !== this.signature(operation, params))
      return null
    if (entry.signature === this.signature(operation, params, bound))
      return null
    this.entries.delete(code)
    return entry.bound
  }
}
