import type { CommandExecutor } from '../executor/types.js'

/**
 * Boot-time import units for ZFS pools (issue #22).
 *
 * A pool created or imported with a bare `zpool create` / `zpool import` is only
 * brought back at boot by /etc/zfs/zpool.cache — which is intermittently
 * unreliable on PVE (a cache written before the pool settles, a cache not
 * regenerated by the initramfs, …), and the symptom is a pool that is simply
 * missing after a reboot. PVE hit this as Proxmox bug #2554 and fixed it in
 * PVE/API2/Disks/ZFS.pm by ALSO enabling the pool's own
 * `zfs-import@<pool>.service` on create (and disabling it on destroy). That unit
 * runs `zpool import <pool>` at boot independently of the cache, so the two
 * mechanisms back each other up.
 *
 * This module is that parity: the escaping PVE gets from `systemd-escape`, the
 * unit name, and a best-effort enable/disable. Nothing here is ANAS state — the
 * unit's enablement lives in systemd, the system remains the source of truth.
 */

const SYSTEMCTL = '/usr/bin/systemctl'

/** Bytes systemd passes through verbatim in a (non-path) instance name. */
const PASS_THROUGH_RE = /[\w:.]/

/**
 * Escape a string for use as a systemd unit INSTANCE name — the pure-TS
 * equivalent of `systemd-escape <name>` (no `--path`), so we never shell out
 * just to name a unit. Mirrors systemd's own `do_escape()`:
 *
 *   - `[A-Za-z0-9:_.]` pass through verbatim
 *   - `/` becomes `-`
 *   - every other byte (UTF-8, so a multi-byte character escapes per byte)
 *     becomes `\x` + its lowercase two-digit hex — note that `-` itself is NOT
 *     a pass-through byte, so `my-pool` escapes to `my\x2dpool`
 *   - a LEADING `.` is escaped (`\x2e`), so no unit is ever named `.something`
 */
export function escapeSystemdInstance(name: string): string {
  const bytes = Buffer.from(name, 'utf-8')
  let escaped = ''
  for (let i = 0; i < bytes.length; i++) {
    const byte = bytes[i]
    const ch = String.fromCharCode(byte)
    if (i === 0 && ch === '.')
      escaped += '\\x2e'
    else if (ch === '/')
      escaped += '-'
    else if (PASS_THROUGH_RE.test(ch))
      escaped += ch
    else
      escaped += `\\x${byte.toString(16).padStart(2, '0')}`
  }
  return escaped
}

/** The boot-import unit for a pool: `zfs-import@<escaped-name>.service`. */
export function zfsImportUnitName(pool: string): string {
  return `zfs-import@${escapeSystemdInstance(pool)}.service`
}

/**
 * Enable (after create/import) or disable (after destroy) a pool's boot-import
 * unit — BEST-EFFORT: never throws, returns null on success and a one-line
 * warning otherwise.
 *
 * The rationale for not failing the job: the primary mutation (create, import,
 * destroy) has ALREADY succeeded by the time this runs, so a unit-management
 * hiccup must not turn a done deal into a failed job — it is reported as a job
 * warning instead. We also skip PVE's `-e /lib/systemd/system/zfs-import@.service`
 * guard: on a PVE node that template always exists (it ships with
 * zfsutils-linux), and if it somehow does not, a failing `systemctl` says so in
 * the warning far more usefully than a silent skip.
 */
export async function syncZfsImportUnit(
  executor: CommandExecutor,
  pool: string,
  action: 'enable' | 'disable',
): Promise<string | null> {
  const unit = zfsImportUnitName(pool)
  try {
    const result = await executor.exec(SYSTEMCTL, [action, unit])
    if (result.exitCode === 0)
      return null
    return `${failurePrefix(action, unit, pool)}: ${result.stderr.trim() || `systemctl ${action} exited with code ${result.exitCode}`}`
  }
  catch (err) {
    return `${failurePrefix(action, unit, pool)}: ${err instanceof Error ? err.message : String(err)}`
  }
}

/** The consequence half of the warning — what the operator actually cares about. */
function failurePrefix(action: 'enable' | 'disable', unit: string, pool: string): string {
  return action === 'enable'
    ? `Could not enable ${unit} — '${pool}' may not be imported automatically after a reboot`
    : `Could not disable ${unit} — a stale boot-import unit may remain for the destroyed pool '${pool}'`
}
