#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=== ANAS Stunt Node — Host Setup ==="
echo

# Check OS
if [ -f /etc/fedora-release ]; then
  echo "✓ Fedora detected: $(cat /etc/fedora-release)"
else
  echo "⚠ This script is designed for Fedora. Other distros may work but are not tested."
fi
echo

# Install packages
PACKAGES="qemu-kvm libvirt libvirt-daemon-kvm virt-install qemu-img genisoimage"
MISSING=""
for pkg in $PACKAGES; do
  if ! rpm -q "$pkg" &>/dev/null; then
    MISSING="$MISSING $pkg"
  fi
done

if [ -n "$MISSING" ]; then
  echo "Installing missing packages:$MISSING"
  sudo dnf install -y $MISSING
else
  echo "✓ All required packages installed"
fi
echo

# KVM modules
if [ -e /dev/kvm ]; then
  echo "✓ KVM available (/dev/kvm exists)"
else
  echo "⚠ KVM not available. Check BIOS virtualization settings."
fi
echo

# Libvirt group
if id -nG "$USER" | grep -qw libvirt; then
  echo "✓ User $(whoami) is in libvirt group"
else
  echo "Adding $(whoami) to libvirt group..."
  sudo usermod -aG libvirt "$USER"
  echo "⚠ You must log out and back in for group membership to take effect."
fi
echo

# Enable libvirtd
if systemctl is-active --quiet libvirtd; then
  echo "✓ libvirtd is running"
else
  echo "Enabling and starting libvirtd..."
  sudo systemctl enable --now libvirtd
fi
echo

# Create network
if sudo virsh net-info anas-test &>/dev/null; then
  echo "✓ anas-test network exists"
else
  echo "Creating anas-test network..."
  sudo virsh net-define "${SCRIPT_DIR}/anas-test-network.xml"
fi

NET_ACTIVE=$(sudo virsh net-info anas-test 2>/dev/null | grep "Active:" | awk '{print $2}')
if [ "$NET_ACTIVE" != "yes" ]; then
  sudo virsh net-start anas-test
fi
sudo virsh net-autostart anas-test 2>/dev/null || true
echo "✓ anas-test network active and set to autostart"
echo

# STORAGE_PATH
if [ -f "${SCRIPT_DIR}/config.local" ]; then
  echo "✓ config.local already exists"
  source "${SCRIPT_DIR}/config.local"
  echo "  STORAGE_PATH=${STORAGE_PATH}"
else
  echo "Where should VM disk images be stored?"
  echo "This directory needs ~50GB of free space."
  read -rp "STORAGE_PATH: " STORAGE_PATH

  if [ -z "$STORAGE_PATH" ]; then
    echo "ERROR: STORAGE_PATH cannot be empty."
    exit 1
  fi

  # Expand ~ if present
  STORAGE_PATH="${STORAGE_PATH/#\~/$HOME}"

  sudo mkdir -p "$STORAGE_PATH"
  sudo chown "$USER:$USER" "$STORAGE_PATH"
  cat > "${SCRIPT_DIR}/config.local" <<EOF
# Developer-local settings — generated by setup-host.sh
# Where to store VM disk images (must have ~50GB free)
STORAGE_PATH="${STORAGE_PATH}"
EOF
  echo "✓ config.local created"
fi
echo

# SSH key
SSH_KEYS=(~/.ssh/id_*.pub)
if [ -e "${SSH_KEYS[0]}" ]; then
  echo "✓ SSH public key found: ${SSH_KEYS[0]}"
else
  echo "No SSH public key found."
  read -rp "Generate one now? [Y/n] " yn
  case "${yn:-Y}" in
    [Nn]*) echo "Skipping. You'll need an SSH key for VM access." ;;
    *)
      ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ""
      echo "✓ SSH key generated"
      ;;
  esac
fi
echo

echo "=== Host setup complete ==="
echo
echo "Next steps:"
echo "  1. Log out and back in (if you were added to the libvirt group)"
echo "  2. Run: ./create-vm.sh"
